name: WeRead to Feishu Sync

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: "0 20 * * *"  # 每天UTC时间20:00（北京时间04:00）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test environment
      env:
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
        FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
      run: npm run test

    - name: Run sync
      env:
        WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
        FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
      run: npm start
